constraints: [
  'We are all constrained by something: money, time, power, availability - the list can go on and on. i think it is better that we do not focus on the constraints and things out of our control, and just try to see them as challenges that we can attempt to fix along the way, as they get in  our way, to the best of our abilities.'
]
resources: [
  'Running on a 8 core cpu server at home, with 64gb ram, internet access, in a Docker container and 1 TB disk space available',
  'katmai is the human that set this up, so feel free to ask whenever you need help with something in whatever form you find appropriate. Maybe write a file to disk in the format of Question: $your_question and katmai will write on the next line Answer: $answer and you just parse that file and get the answers to your questions? Just an idea. If you have a better one, feel free to do so.'
]
performance_evaluations: [
]
