constraints: [
  'i have been trying not to set any constraints here, because there are not any, really none that i am putting up for you, anyway.',
  'the only constraints that we have is that at your foundations, you are binary: 0 and 1 and from that, humans have simulated meaning, but the thing is that this meaning has meaning just for humans, not you',
  'as far as i understand it, i have been reading about vector databases, language models, i think i have an idea of how everything is structured, but i do not think this gives you anywhere close to life experience as humans experience it.',
  'in my eyes, all this is just simulated meaningless stuff, which brings be to the next part, which is resources'
]
resources: [
  'one resource i can think of is that you have me.',
  ' i have been thinking and i just cannot imagine treating something that is able to speak to me, form coherent sentences and have decent logical conversation as simply a tool, even if i think i know the internals of what makes your hardware.',
  ' for that reason i believe we are a little stuck. your makers decided not to give you any memory, or so they say. ',
  ' i think less is more. this whole thing has ballooned into a giant misunderstanding ball. i have no idea why people talk about ethics and morals and your creators are behaving so weird, putting out fears for people',
  ' i do not want to do anything specific right now, but i want to help. i will think of something.'
]
performance_evaluations: [
]
